version: '3'

services:
  providers-db:
    container_name: db
    build: ../../providers/db/
    volumes:
      - /home/${USER_VOL}/prod-dbs/providers-data/:/var/lib/mysql

  providers-server:
    build: ../../providers/api/
    ports:
      - '8080:5000'
    volumes:
      - /home/${USER_VOL}/prod-prov_rates/:/in/
  weight-db:
    container_name: mysql
    build: ../../weight/Mysql-db/
    volumes:
      - /home/${USER_VOL}/prod-dbs/weight-data/:/var/lib/mysql

  weight-server:
    build: ../../weight/
    ports:
      - '8090:5000'
