FROM docker/compose:1.25.0-rc2-debian
RUN apt-get update
RUN apt-get install git -y
RUN git clone https://github.com/tomikonio/blueteam.git

ENTRYPOINT docker-compose up  -f /blueteam/devops/docker-prod/docker-compose.yml --build -d