FROM docker/compose:1.25.0-rc2-debian
RUN apt-get update
RUN apt-get install git -y
RUN git clone https://github.com/tomikonio/blueteam.git
RUN apt-get install python -y
RUN apt-get install python-pip -y 
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT flask run --host=0.0.0.0
