version: '3'

services:
  web-ci:
    build: .
    ports:
      - '8085:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - USER_VOL=${USER}
    # volumes:
    #   - ../../providers/:/providers
    #   - ../../weight/:/weight
    #   - ../../devops/:/devops
