version: "3"

services:
  weight-db:
    container_name: mysql
    build: ./Mysql-db
    ports:
      - "3306:3306"
    volumes:
       - ~/prod-dbs/weight-data/:/var/lib/mysql
       #- ./Mysql-db/weight-db.sql:/docker-entrypoint-initdb.d/weight-db.sql
  weight-server:
    build: .
    depends_on:
      - weight-db
    ports:
      - "5000:5000"
